import assert from 'node:assert/strict';
import { chromium } from 'playwright';

const base = process.env.E2E_BASE_URL || 'http://localhost:8001';
const browser = await chromium.launch({ headless: true, executablePath: process.env.E2E_BROWSER_PATH || 'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe' });
try {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'no-preference' });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(base);
  await page.getByRole('dialog', { name: '演武堂开场动画' }).waitFor({ state: 'detached' });
  await page.locator('.arena-ambient').waitFor({ state: 'attached' });
  const card = page.locator('.arena-catalog-card').first();
  await card.scrollIntoViewIfNeeded();
  await page.evaluate(() => new Promise(resolve => requestAnimationFrame(() => requestAnimationFrame(resolve))));
  await card.hover();
  await page.waitForFunction(() => document.querySelector('.arena-catalog-card')?.hasAttribute('data-glass-active'));
  const light = await card.evaluate(el => ({ x: el.style.getPropertyValue('--light-x'), transform: el.style.transform, shadow: el.style.boxShadow }));
  assert.ok(light.x.endsWith('px'), 'Pointer lights the card under the cursor');
  assert.equal(light.transform, '', 'Lighting does not overwrite component transforms');
  assert.equal(light.shadow, '', 'Lighting does not overwrite component shadows');
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.waitForFunction(() => !document.querySelector('[data-glass-active]'));
  assert.equal(await card.evaluate(el => el.style.getPropertyValue('--light-x')), '', 'Motion preference change clears lighting');
  await page.mouse.move(0, 0); await card.hover();
  assert.equal(await page.locator('[data-glass-active]').count(), 0, 'Reduced motion stays still after mouse movement');
  await page.emulateMedia({ reducedMotion: 'no-preference' });
  await page.mouse.move(0, 0); await card.hover();
  await page.waitForFunction(() => document.querySelector('[data-glass-active]'));
  await page.mouse.wheel(0, -400);
  await page.waitForFunction(() => !document.querySelector('[data-glass-active]'));
  await page.mouse.move(0, 0); await page.evaluate(() => scrollTo(0, 0));
  await page.screenshot({ path: '.cache/arena-redesign/glass-desktop.png', fullPage: true });
  await context.close();

  const mobile = await browser.newContext({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, reducedMotion: 'reduce', userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 18_0 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148 Safari/604.1' });
  const phone = await mobile.newPage();
  phone.on('pageerror', error => errors.push(error.message));
  await phone.goto(base);
  const dock = phone.getByRole('navigation', { name: '底部导航' });
  await dock.waitFor();
  await phone.getByRole('button', { name: '打开图鉴菜单' }).tap();
  const selection = phone.locator('.arena-dock-selection');
  assert.equal(await selection.getAttribute('data-index'), '2', 'Glass selection follows the opened catalog');
  await phone.getByRole('button', { name: '关闭图鉴菜单' }).tap();
  assert.equal(await selection.getAttribute('data-index'), '0', 'Closing catalog restores the current route selection');
  await dock.getByRole('link', { name: '赛事', exact: true }).tap();
  await phone.waitForURL(/\/m\/tournaments/);
  assert.equal(await selection.getAttribute('data-index'), '1');
  assert.equal(await phone.locator('[data-glass-active]').count(), 0, 'Touch does not enable cursor light');
  assert.ok(await phone.evaluate(() => document.documentElement.scrollWidth <= innerWidth), 'No mobile overflow');
  await dock.getByRole('link', { name: '首页', exact: true }).tap();
  await phone.waitForURL(/\/m\/?$/);
  await phone.screenshot({ path: '.cache/arena-redesign/glass-mobile.png', fullPage: true });
  await mobile.close();
  assert.deepEqual(errors, []);
  console.log('Glass interaction passed: pointer light, cleanup, dynamic reduced motion, touch, dock selection, mobile routing and runtime errors.');
} finally { await browser.close(); }
