// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../src/app/admin/announcements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/announcements">> = Specific
  const handler = {} as typeof import("../../src/app/admin/announcements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/heroes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/heroes">> = Specific
  const handler = {} as typeof import("../../src/app/admin/heroes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/tournaments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/tournaments">> = Specific
  const handler = {} as typeof import("../../src/app/admin/tournaments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/changelog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/changelog/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/changelog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/changelog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/changelog">> = Specific
  const handler = {} as typeof import("../../src/app/changelog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/combat/[postId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/combat/[postId]">> = Specific
  const handler = {} as typeof import("../../src/app/combat/[postId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/combat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/combat">> = Specific
  const handler = {} as typeof import("../../src/app/combat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/debug/login-effect/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/debug/login-effect">> = Specific
  const handler = {} as typeof import("../../src/app/debug/login-effect/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/debug/orb-colors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/debug/orb-colors">> = Specific
  const handler = {} as typeof import("../../src/app/debug/orb-colors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/debug/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/debug">> = Specific
  const handler = {} as typeof import("../../src/app/debug/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/equipment/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/equipment/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/equipment/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/equipment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/equipment">> = Specific
  const handler = {} as typeof import("../../src/app/equipment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/heroes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/heroes/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/heroes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/heroes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/heroes">> = Specific
  const handler = {} as typeof import("../../src/app/heroes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/login">> = Specific
  const handler = {} as typeof import("../../src/app/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/admin/announcements/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/admin/announcements">> = Specific
  const handler = {} as typeof import("../../src/app/m/admin/announcements/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/admin/heroes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/admin/heroes">> = Specific
  const handler = {} as typeof import("../../src/app/m/admin/heroes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/admin">> = Specific
  const handler = {} as typeof import("../../src/app/m/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/admin/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/m/admin/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/admin/tournaments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/admin/tournaments">> = Specific
  const handler = {} as typeof import("../../src/app/m/admin/tournaments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/admin/users/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/m/admin/users/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/changelog/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/changelog/[slug]">> = Specific
  const handler = {} as typeof import("../../src/app/m/changelog/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/changelog/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/changelog">> = Specific
  const handler = {} as typeof import("../../src/app/m/changelog/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/combat/[postId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/combat/[postId]">> = Specific
  const handler = {} as typeof import("../../src/app/m/combat/[postId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/combat/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/combat">> = Specific
  const handler = {} as typeof import("../../src/app/m/combat/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/debug/login-effect/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/debug/login-effect">> = Specific
  const handler = {} as typeof import("../../src/app/m/debug/login-effect/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/debug/orb-colors/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/debug/orb-colors">> = Specific
  const handler = {} as typeof import("../../src/app/m/debug/orb-colors/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/debug/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/debug">> = Specific
  const handler = {} as typeof import("../../src/app/m/debug/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/equipment/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/equipment/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/m/equipment/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/equipment/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/equipment">> = Specific
  const handler = {} as typeof import("../../src/app/m/equipment/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/heroes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/heroes/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/m/heroes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/heroes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/heroes">> = Specific
  const handler = {} as typeof import("../../src/app/m/heroes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/login">> = Specific
  const handler = {} as typeof import("../../src/app/m/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/me/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/me">> = Specific
  const handler = {} as typeof import("../../src/app/m/me/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/monitor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/monitor">> = Specific
  const handler = {} as typeof import("../../src/app/m/monitor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m">> = Specific
  const handler = {} as typeof import("../../src/app/m/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/register">> = Specific
  const handler = {} as typeof import("../../src/app/m/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/tournaments/[id]/matches/[matchId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/tournaments/[id]/matches/[matchId]">> = Specific
  const handler = {} as typeof import("../../src/app/m/tournaments/[id]/matches/[matchId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/tournaments/[id]/matches/[matchId]/tactics/[side]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/tournaments/[id]/matches/[matchId]/tactics/[side]">> = Specific
  const handler = {} as typeof import("../../src/app/m/tournaments/[id]/matches/[matchId]/tactics/[side]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/tournaments/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/tournaments/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/m/tournaments/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/tournaments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/m/tournaments">> = Specific
  const handler = {} as typeof import("../../src/app/m/tournaments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/me/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/me">> = Specific
  const handler = {} as typeof import("../../src/app/me/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/monitor/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/monitor">> = Specific
  const handler = {} as typeof import("../../src/app/monitor/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/register/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/register">> = Specific
  const handler = {} as typeof import("../../src/app/register/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tournaments/[id]/matches/[matchId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tournaments/[id]/matches/[matchId]">> = Specific
  const handler = {} as typeof import("../../src/app/tournaments/[id]/matches/[matchId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tournaments/[id]/matches/[matchId]/tactics/[side]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tournaments/[id]/matches/[matchId]/tactics/[side]">> = Specific
  const handler = {} as typeof import("../../src/app/tournaments/[id]/matches/[matchId]/tactics/[side]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tournaments/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tournaments/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/tournaments/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/tournaments/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tournaments">> = Specific
  const handler = {} as typeof import("../../src/app/tournaments/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/announcements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/announcements">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/announcements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/matches/[matchId]/corrections/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/matches/[matchId]/corrections">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/matches/[matchId]/corrections/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/resources/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/resources">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/resources/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/settings">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/stats/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/stats">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/stats/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/sync-status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/sync-status">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/sync-status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/tournaments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/tournaments">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/tournaments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/admin/users/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/users">> = Specific
  const handler = {} as typeof import("../../src/app/api/admin/users/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/announcements/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/announcements/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/announcements/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/announcements/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/announcements">> = Specific
  const handler = {} as typeof import("../../src/app/api/announcements/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/change-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/change-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/change-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/login">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/logout">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/me/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/me">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/me/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/register/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/register">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/register/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/reset-password/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/reset-password">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/reset-password/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/auth/security-question/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/security-question">> = Specific
  const handler = {} as typeof import("../../src/app/api/auth/security-question/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/avatars/[filename]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/avatars/[filename]">> = Specific
  const handler = {} as typeof import("../../src/app/api/avatars/[filename]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/changelog/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/changelog">> = Specific
  const handler = {} as typeof import("../../src/app/api/changelog/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/combat-posts/[postId]/comments/[commentId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/combat-posts/[postId]/comments/[commentId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/combat-posts/[postId]/comments/[commentId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/combat-posts/[postId]/comments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/combat-posts/[postId]/comments">> = Specific
  const handler = {} as typeof import("../../src/app/api/combat-posts/[postId]/comments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/combat-posts/[postId]/like/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/combat-posts/[postId]/like">> = Specific
  const handler = {} as typeof import("../../src/app/api/combat-posts/[postId]/like/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/combat-posts/[postId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/combat-posts/[postId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/combat-posts/[postId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/combat-posts/[postId]/video/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/combat-posts/[postId]/video">> = Specific
  const handler = {} as typeof import("../../src/app/api/combat-posts/[postId]/video/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/combat-posts/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/combat-posts">> = Specific
  const handler = {} as typeof import("../../src/app/api/combat-posts/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/equipment/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/equipment/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/equipment/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/equipment/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/equipment">> = Specific
  const handler = {} as typeof import("../../src/app/api/equipment/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/health">> = Specific
  const handler = {} as typeof import("../../src/app/api/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/heroes/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/heroes/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/heroes/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/heroes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/heroes">> = Specific
  const handler = {} as typeof import("../../src/app/api/heroes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/heroes/watch/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/heroes/watch">> = Specific
  const handler = {} as typeof import("../../src/app/api/heroes/watch/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/me/avatar/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/avatar">> = Specific
  const handler = {} as typeof import("../../src/app/api/me/avatar/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/me/profile/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/me/profile">> = Specific
  const handler = {} as typeof import("../../src/app/api/me/profile/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/official-news/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/official-news">> = Specific
  const handler = {} as typeof import("../../src/app/api/official-news/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/resources/data/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/resources/data">> = Specific
  const handler = {} as typeof import("../../src/app/api/resources/data/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/resources/leases/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/resources/leases">> = Specific
  const handler = {} as typeof import("../../src/app/api/resources/leases/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tournaments/[id]/admin/resign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[id]/admin/resign">> = Specific
  const handler = {} as typeof import("../../src/app/api/tournaments/[id]/admin/resign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tournaments/[id]/admin/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[id]/admin">> = Specific
  const handler = {} as typeof import("../../src/app/api/tournaments/[id]/admin/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tournaments/[id]/extend/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[id]/extend">> = Specific
  const handler = {} as typeof import("../../src/app/api/tournaments/[id]/extend/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tournaments/[id]/join/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[id]/join">> = Specific
  const handler = {} as typeof import("../../src/app/api/tournaments/[id]/join/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tournaments/[id]/kick/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[id]/kick">> = Specific
  const handler = {} as typeof import("../../src/app/api/tournaments/[id]/kick/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tournaments/[id]/leave/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[id]/leave">> = Specific
  const handler = {} as typeof import("../../src/app/api/tournaments/[id]/leave/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tournaments/[id]/matches/[matchId]/confirmation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[id]/matches/[matchId]/confirmation">> = Specific
  const handler = {} as typeof import("../../src/app/api/tournaments/[id]/matches/[matchId]/confirmation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tournaments/[id]/matches/[matchId]/disputes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[id]/matches/[matchId]/disputes">> = Specific
  const handler = {} as typeof import("../../src/app/api/tournaments/[id]/matches/[matchId]/disputes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tournaments/[id]/matches/[matchId]/recognitions/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[id]/matches/[matchId]/recognitions">> = Specific
  const handler = {} as typeof import("../../src/app/api/tournaments/[id]/matches/[matchId]/recognitions/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tournaments/[id]/matches/[matchId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[id]/matches/[matchId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/tournaments/[id]/matches/[matchId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tournaments/[id]/matches/[matchId]/screenshots/[type]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[id]/matches/[matchId]/screenshots/[type]">> = Specific
  const handler = {} as typeof import("../../src/app/api/tournaments/[id]/matches/[matchId]/screenshots/[type]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tournaments/[id]/matches/[matchId]/submit/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[id]/matches/[matchId]/submit">> = Specific
  const handler = {} as typeof import("../../src/app/api/tournaments/[id]/matches/[matchId]/submit/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tournaments/[id]/matches/[matchId]/tactics/[side]/layers/[layerId]/markers/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[id]/matches/[matchId]/tactics/[side]/layers/[layerId]/markers">> = Specific
  const handler = {} as typeof import("../../src/app/api/tournaments/[id]/matches/[matchId]/tactics/[side]/layers/[layerId]/markers/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tournaments/[id]/matches/[matchId]/tactics/[side]/layers/[layerId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[id]/matches/[matchId]/tactics/[side]/layers/[layerId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/tournaments/[id]/matches/[matchId]/tactics/[side]/layers/[layerId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tournaments/[id]/matches/[matchId]/tactics/[side]/layers/[layerId]/route/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[id]/matches/[matchId]/tactics/[side]/layers/[layerId]/route">> = Specific
  const handler = {} as typeof import("../../src/app/api/tournaments/[id]/matches/[matchId]/tactics/[side]/layers/[layerId]/route/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tournaments/[id]/matches/[matchId]/tactics/[side]/markers/[markerId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[id]/matches/[matchId]/tactics/[side]/markers/[markerId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/tournaments/[id]/matches/[matchId]/tactics/[side]/markers/[markerId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tournaments/[id]/matches/[matchId]/tactics/[side]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[id]/matches/[matchId]/tactics/[side]">> = Specific
  const handler = {} as typeof import("../../src/app/api/tournaments/[id]/matches/[matchId]/tactics/[side]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tournaments/[id]/matches/[matchId]/tactics/[side]/routes/[routeId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[id]/matches/[matchId]/tactics/[side]/routes/[routeId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/tournaments/[id]/matches/[matchId]/tactics/[side]/routes/[routeId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tournaments/[id]/matches/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[id]/matches">> = Specific
  const handler = {} as typeof import("../../src/app/api/tournaments/[id]/matches/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tournaments/[id]/picks/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[id]/picks">> = Specific
  const handler = {} as typeof import("../../src/app/api/tournaments/[id]/picks/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tournaments/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[id]">> = Specific
  const handler = {} as typeof import("../../src/app/api/tournaments/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tournaments/[id]/split/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[id]/split">> = Specific
  const handler = {} as typeof import("../../src/app/api/tournaments/[id]/split/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tournaments/[id]/temp-application/[appId]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[id]/temp-application/[appId]">> = Specific
  const handler = {} as typeof import("../../src/app/api/tournaments/[id]/temp-application/[appId]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tournaments/[id]/temp-application/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[id]/temp-application">> = Specific
  const handler = {} as typeof import("../../src/app/api/tournaments/[id]/temp-application/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tournaments/[id]/temp-player/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/[id]/temp-player">> = Specific
  const handler = {} as typeof import("../../src/app/api/tournaments/[id]/temp-player/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tournaments/join-by-code/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/join-by-code">> = Specific
  const handler = {} as typeof import("../../src/app/api/tournaments/join-by-code/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tournaments/public/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments/public">> = Specific
  const handler = {} as typeof import("../../src/app/api/tournaments/public/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/tournaments/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/tournaments">> = Specific
  const handler = {} as typeof import("../../src/app/api/tournaments/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/me/heroes/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/me/heroes">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/me/heroes/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/api/users/me/roles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/users/me/roles">> = Specific
  const handler = {} as typeof import("../../src/app/api/users/me/roles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../src/app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../src/app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/debug/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/debug">> = Specific
  const handler = {} as typeof import("../../src/app/debug/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../src/app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/m/admin">> = Specific
  const handler = {} as typeof import("../../src/app/m/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/debug/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/m/debug">> = Specific
  const handler = {} as typeof import("../../src/app/m/debug/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../src/app/m/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/m">> = Specific
  const handler = {} as typeof import("../../src/app/m/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
